sudo: false
language: python
env:


matrix:
    include:
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"
        - DOC_BUILD="true"
    - python: 3.7
      sudo: yes
      dist: xenial
      env:
        - PYTHON_VERSION="3.7"
        - DOC_BUILD="true"
install:
    - source continuous_integration/install.sh
script:
    - eval xvfb-run pytest
    - flake8 --max-line-length=115 --ignore=F401,E402,W504,W605

